### ISSUE TITLE
 Could not find Custom Field: plugin::ckeditor5video.CKEditor5Video

### ISSUE THREAD

**Issue by vinubabu323** [hrahimi270/strapi-plugin-ckeditor-video#1]
![plugin-error](https://github.com/hrahimi270/strapi-plugin-ckeditor-video/assets/72564243/fbc3633a-f764-4da4-b333-c843602d5ce6)

This error is showing in application.

**Comment by vinubabu323** [comment]
Strapi version : 4.10.4 (node v16.16.0)

**Comment by m7jxc** [comment]
same error. any solutions?

**Comment by mplutka** [comment]
Inside server/register.js
name needs to be 'CKEditor5Video'

**Comment by hrahimi270** [comment]
@vinubabu323 @m7jxc @mplutka  Sorry for so late respond. The problem is fixed on version 0.0.5.
